### ISSUE TITLE
训练数据链接

### ISSUE THREAD

**Issue by MikeDai2019** [CrazySummerday/ctpn.pytorch#1]
能不能把训练数据链接贴一下，我找了好几个ICDAR 2017的链接，感觉都不对，谢谢！

**Comment by CrazySummerday** [comment]
https://rctw.vlrlab.net/dataset/

**Comment by CrazySummerday** [comment]
> 能不能把训练数据链接贴一下，我找了好几个ICDAR 2017的链接，感觉都不对，谢谢！

https://rctw.vlrlab.net/dataset/

**Comment by MikeDai2019** [comment]
谢谢！
